import { mockIp, mockReqId } from '../utils/mock';

export function genCartGroupData() {
  return {
    data: {
      isNotEmpty: true,
      storeGoods: [
        {
          storeId: '1000',
          storeName: '知参堂',
          storeStatus: 1,
          totalDiscountSalePrice: '13980',
          promotionGoodsList: [
            {
              title: '黑参液礼盒促销',
              promotionCode: 'MERCHANT',
              promotionSubCode: 'MYJ',
              promotionId: 'zhishentang-promotion',
              tagText: ['黑参液礼盒促销'],
              promotionStatus: 3,
              tag: '促销',
              description: '知参堂精选参加工产品',
              doorSillRemain: null,
              isNeedAddOnShop: 0,
              goodsPromotionList: [
                {
                  uid: 'zhishentang-cart-1001',
                  saasId: 'zhishentang',
                  storeId: '1000',
                  spuId: '1001',
                  skuId: 'sku-1001',
                  isSelected: 1,
                  thumb: '/images/products/image-1.jpeg',
                  title: '黑参液',
                  primaryImage: '/images/products/image-1.jpeg',
                  quantity: 1,
                  stockStatus: true,
                  stockQuantity: 99,
                  price: '6990',
                  originPrice: '9990',
                  tagPrice: null,
                  titlePrefixTags: [{ text: '礼盒促销' }],
                  roomId: null,
                  specInfo: [{ specTitle: '规格', specValue: '20袋' }],
                  joinCartTime: '2026-05-06T00:00:00.000+0000',
                  available: 1,
                  putOnSale: 1,
                  etitle: null,
                },
                {
                  uid: 'zhishentang-cart-1002',
                  saasId: 'zhishentang',
                  storeId: '1000',
                  spuId: '1002',
                  skuId: 'sku-1002',
                  isSelected: 1,
                  thumb: '/images/products/image-2.jpeg',
                  title: '红参膏',
                  primaryImage: '/images/products/image-2.jpeg',
                  quantity: 1,
                  stockStatus: true,
                  stockQuantity: 99,
                  price: '6990',
                  originPrice: '9990',
                  tagPrice: null,
                  titlePrefixTags: [{ text: '精选好物' }],
                  roomId: null,
                  specInfo: [{ specTitle: '规格', specValue: '200g' }],
                  joinCartTime: '2026-05-06T00:00:00.000+0000',
                  available: 1,
                  putOnSale: 1,
                  etitle: null,
                },
              ],
              lastJoinTime: null,
            },
          ],
          lastJoinTime: '2026-05-06T00:00:00.000+0000',
          postageFreePromotionVo: {
            title: null,
            promotionCode: null,
            promotionSubCode: null,
            promotionId: null,
            tagText: null,
            promotionStatus: null,
            tag: null,
            description: null,
            doorSillRemain: null,
            isNeedAddOnShop: 0,
          },
        },
      ],
      invalidGoodItems: [],
      isAllSelected: true,
      selectedGoodsCount: 2,
      totalAmount: '19980',
      totalDiscountAmount: '6000',
    },
    code: 'Success',
    msg: null,
    requestId: mockReqId(),
    clientIp: mockIp(),
    rt: 269,
    success: true,
  };
}
